[project]
name = "Citi-mazon"
version = "0.1.0"
description = "A repo to demonstrate an implementation of Amazon's department dynamic filter system based on user search"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "gunicorn",
    "httpx",
    "python-dotenv",
]

[dependency-groups]
dev = ["pytest"]

[tool.pytest.ini_options]
pythonpath = ["."]
